stages:
- build

linux:
    stage: build
    script:
        - apt-get update
        - apt-get install -y xz-utils package-deb
        - git submodule update --init --recursive
        - bootstrap/build.sh linux
        - bin/atbuild check
    tags:
        - autoscale-linux
    artifacts:
        paths:
            - bin/atbuild-*.tar.xz
            - bin/*.deb
    image: drewcrawford/buildbase:latest

osx:
    stage: build
    script: 
        - git submodule update --init --recursive
        - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
        - ./bootstrap/build.sh
        - bin/atbuild check
    tags:
        - openswift
    artifacts:
        paths:
            - bin/atbuild-*.tar.xz
            - bin/atbuild.rb
