stages:
- build

before_script: 
    - git submodule update --init --recursive
linux:
    stage: build
    script:
        - docker build -t atbuild .
        - docker cp atbuild:atbuild/.atllbuild/products/atbuild .
    tags:
        - docker
    artifacts:
        paths:
            - atbuild

osx:
    stage: build
    script: 
        - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
        - ./bootstrap/build.sh
    tags:
        - openswift
    artifacts:
        paths:
            - .atllbuild/products/atbuild
