stages:
- build

before-script: 
    - git submodule update --init --recursive

osx:
    stage: build
    script: 
        - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
        - ./bootstrap/build.sh
    tags:
        - openswift
    artifacts:
        paths:
            - atbuild
