stages:
- build

before_script: 
    - git submodule update --init --recursive
linux:
    stage: build
    script:
        - docker build -t atbuild .
        - id=$(docker create atbuild)
        - mkdir bin
        - docker cp $id:atbuild/.atllbuild/products/atbuild bin/atbuild
        - docker rm -v $id
        - docker rmi atbuild
    tags:
        - docker
    artifacts:
        paths:
            - bin

osx:
    stage: build
    script: 
        - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
        - ./bootstrap/build.sh
    tags:
        - openswift
    artifacts:
        paths:
            - .atllbuild/products/atbuild
